// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO7cAe_BNOe3zvXkI_1YmUW90QO-2corQ',
    appId: '1:615067178353:web:cf713480ada47da0b912d0',
    messagingSenderId: '615067178353',
    projectId: 'ystore-ee918',
    authDomain: 'ystore-ee918.firebaseapp.com',
    storageBucket: 'ystore-ee918.appspot.com',
    measurementId: 'G-BJGBXS9QQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMPlLPGuxXtgcMe1zvvHewgV9xN9r5Dok',
    appId: '1:615067178353:android:f652204d1128e91cb912d0',
    messagingSenderId: '615067178353',
    projectId: 'ystore-ee918',
    storageBucket: 'ystore-ee918.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpjqVDe_2_DUBO30q0YnZjsOA-GqS1SlU',
    appId: '1:615067178353:ios:f5e05f7c729fbd9bb912d0',
    messagingSenderId: '615067178353',
    projectId: 'ystore-ee918',
    storageBucket: 'ystore-ee918.appspot.com',
    iosBundleId: 'com.example.ystore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpjqVDe_2_DUBO30q0YnZjsOA-GqS1SlU',
    appId: '1:615067178353:ios:f5e05f7c729fbd9bb912d0',
    messagingSenderId: '615067178353',
    projectId: 'ystore-ee918',
    storageBucket: 'ystore-ee918.appspot.com',
    iosBundleId: 'com.example.ystore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO7cAe_BNOe3zvXkI_1YmUW90QO-2corQ',
    appId: '1:615067178353:web:47e4a9dd9396c8e6b912d0',
    messagingSenderId: '615067178353',
    projectId: 'ystore-ee918',
    authDomain: 'ystore-ee918.firebaseapp.com',
    storageBucket: 'ystore-ee918.appspot.com',
    measurementId: 'G-T1SH6XT8XS',
  );
}
